# Generated by Hype
require_relative 'domain.hddl'

# Predicates
SNAKE = [
  :viper
]
LOCATION = [
  :px0y0,
  :px1y0,
  :px2y0,
  :px3y0,
  :px0y1,
  :px1y1,
  :px2y1,
  :px3y1,
  :px0y2,
  :px1y2,
  :px2y2,
  :px3y2,
  :px0y3,
  :px1y3,
  :px2y3,
  :px3y3,
  :px0y4,
  :px1y4,
  :px2y4,
  :px3y4,
  :px0y5,
  :px1y5,
  :px2y5,
  :px3y5
]
MOUSE_AT = 0
HEAD = 1
ADJACENT = [
  [:px0y0, :px1y0],
  [:px1y0, :px0y0],
  [:px1y0, :px2y0],
  [:px2y0, :px1y0],
  [:px2y0, :px3y0],
  [:px3y0, :px2y0],
  [:px0y1, :px1y1],
  [:px1y1, :px0y1],
  [:px1y1, :px2y1],
  [:px2y1, :px1y1],
  [:px2y1, :px3y1],
  [:px3y1, :px2y1],
  [:px0y2, :px1y2],
  [:px1y2, :px0y2],
  [:px1y2, :px2y2],
  [:px2y2, :px1y2],
  [:px2y2, :px3y2],
  [:px3y2, :px2y2],
  [:px0y3, :px1y3],
  [:px1y3, :px0y3],
  [:px1y3, :px2y3],
  [:px2y3, :px1y3],
  [:px2y3, :px3y3],
  [:px3y3, :px2y3],
  [:px0y4, :px1y4],
  [:px1y4, :px0y4],
  [:px1y4, :px2y4],
  [:px2y4, :px1y4],
  [:px2y4, :px3y4],
  [:px3y4, :px2y4],
  [:px0y5, :px1y5],
  [:px1y5, :px0y5],
  [:px1y5, :px2y5],
  [:px2y5, :px1y5],
  [:px2y5, :px3y5],
  [:px3y5, :px2y5],
  [:px0y0, :px0y1],
  [:px0y1, :px0y0],
  [:px1y0, :px1y1],
  [:px1y1, :px1y0],
  [:px2y0, :px2y1],
  [:px2y1, :px2y0],
  [:px3y0, :px3y1],
  [:px3y1, :px3y0],
  [:px0y1, :px0y2],
  [:px0y2, :px0y1],
  [:px1y1, :px1y2],
  [:px1y2, :px1y1],
  [:px2y1, :px2y2],
  [:px2y2, :px2y1],
  [:px3y1, :px3y2],
  [:px3y2, :px3y1],
  [:px0y2, :px0y3],
  [:px0y3, :px0y2],
  [:px1y2, :px1y3],
  [:px1y3, :px1y2],
  [:px2y2, :px2y3],
  [:px2y3, :px2y2],
  [:px3y2, :px3y3],
  [:px3y3, :px3y2],
  [:px0y3, :px0y4],
  [:px0y4, :px0y3],
  [:px1y3, :px1y4],
  [:px1y4, :px1y3],
  [:px2y3, :px2y4],
  [:px2y4, :px2y3],
  [:px3y3, :px3y4],
  [:px3y4, :px3y3],
  [:px0y4, :px0y5],
  [:px0y5, :px0y4],
  [:px1y4, :px1y5],
  [:px1y5, :px1y4],
  [:px2y4, :px2y5],
  [:px2y5, :px2y4],
  [:px3y4, :px3y5],
  [:px3y5, :px3y4]
]
EQUAL = [
  [:viper, :viper],
  [:px0y0, :px0y0],
  [:px1y0, :px1y0],
  [:px2y0, :px2y0],
  [:px3y0, :px3y0],
  [:px0y1, :px0y1],
  [:px1y1, :px1y1],
  [:px2y1, :px2y1],
  [:px3y1, :px3y1],
  [:px0y2, :px0y2],
  [:px1y2, :px1y2],
  [:px2y2, :px2y2],
  [:px3y2, :px3y2],
  [:px0y3, :px0y3],
  [:px1y3, :px1y3],
  [:px2y3, :px2y3],
  [:px3y3, :px3y3],
  [:px0y4, :px0y4],
  [:px1y4, :px1y4],
  [:px2y4, :px2y4],
  [:px3y4, :px3y4],
  [:px0y5, :px0y5],
  [:px1y5, :px1y5],
  [:px2y5, :px2y5],
  [:px3y5, :px3y5]
]
OCCUPIED = 2
CONNECTED = 3
TAIL = 4

Snake.problem(
  # Start
  [
    [
      :px0y5,
      :px1y5,
      :px2y5,
      :px3y5
    ],
    [
      [:viper, :px3y0]
    ],
    [
      :px0y0,
      :px1y0,
      :px2y0,
      :px3y0,
      :px0y1,
      :px0y2,
      :px0y3,
      :px0y4,
      :px1y4,
      :px2y4,
      :px3y4,
      :px0y5,
      :px1y5,
      :px2y5,
      :px3y5
    ],
    [
      [:viper, :px3y0, :px2y0],
      [:viper, :px2y0, :px1y0],
      [:viper, :px1y0, :px0y0],
      [:viper, :px0y0, :px0y1],
      [:viper, :px0y1, :px0y2],
      [:viper, :px0y2, :px0y3],
      [:viper, :px0y3, :px0y4],
      [:viper, :px0y4, :px1y4],
      [:viper, :px1y4, :px2y4],
      [:viper, :px2y4, :px3y4]
    ],
    [
      [:viper, :px3y4]
    ],
  ],
  # Tasks
  [
    [:hunt]
  ],
  # Debug
  ARGV.first == 'debug'
)