# Generated by Hype
require_relative 'domain.hddl'

# Predicates
ROOM = [
  :c,
  :r1,
  :r2,
  :r3,
  :r4
]
PACKAGE = [
  :o1,
  :o2,
  :o3,
  :o4,
  :o5
]
RLOC = 0
HOLDING = 1
GOAL_IN = [
  [:o1, :r4],
  [:o2, :r4],
  [:o3, :r2],
  [:o4, :r4],
  [:o5, :r2]
]
IN = 2
ROOMDOOR = [
  :d24,
  :d04,
  :d03,
  :d14
]
ARMEMPTY = 3
DOOR = [
  [:c, :r3, :d03],
  [:c, :r4, :d04],
  [:r1, :r4, :d14],
  [:r2, :r4, :d24],
  [:r3, :c, :d03],
  [:r4, :c, :d04],
  [:r4, :r1, :d14],
  [:r4, :r2, :d24]
]
CLOSED = 4

Robot.problem(
  # Start
  [
    [
      :c
    ],
    [],
    [
      [:o1, :r2],
      [:o2, :r3],
      [:o3, :r4],
      [:o4, :r2],
      [:o5, :r1]
    ],
    [
      []
    ],
    [
      :d24,
      :d04
    ],
  ],
  # Tasks
  [
    [:achieve_goals],
    [:invisible_goal]
  ],
  # Debug
  ARGV.first == 'debug'
)