# Generated by Hype
require_relative 'domain.hddl'

# Predicates
ROOM = [
  :c,
  :r1
]
PACKAGE = [
  :o1
]
RLOC = 0
HOLDING = 1
GOAL_IN = [
  [:o1, :r1]
]
IN = 2
ROOMDOOR = [
  :d01
]
ARMEMPTY = 3
DOOR = [
  [:c, :r1, :d01],
  [:r1, :c, :d01]
]
CLOSED = 4

Robot.problem(
  # Start
  [
    [
      :c
    ],
    [],
    [
      [:o1, :r1]
    ],
    [
      []
    ],
    [
      :d01
    ],
  ],
  # Tasks
  [
    [:achieve_goals],
    [:invisible_goal]
  ],
  # Debug
  ARGV.first == 'debug'
)