# Generated by Hype
require_relative 'domain.hddl'

# Predicates
ROOM = [
  :c,
  :r1,
  :r2
]
PACKAGE = [
  :o1,
  :o2
]
RLOC = 0
HOLDING = 1
GOAL_IN = [
  [:o1, :r1],
  [:o2, :r2]
]
IN = 2
ROOMDOOR = [
  :d12,
  :d02
]
ARMEMPTY = 3
DOOR = [
  [:c, :r2, :d02],
  [:r1, :r2, :d12],
  [:r2, :c, :d02],
  [:r2, :r1, :d12]
]
CLOSED = 4

Robot.problem(
  # Start
  [
    [
      :c
    ],
    [],
    [
      [:o1, :r1],
      [:o2, :r1]
    ],
    [
      []
    ],
    [
      :d12,
      :d02
    ],
  ],
  # Tasks
  [
    [:achieve_goals],
    [:invisible_goal]
  ],
  # Debug
  ARGV.first == 'debug'
)