# Generated by Hype
require_relative 'domain.hddl'

# Predicates
ROOM = [
  :c,
  :r1,
  :r2,
  :r3,
  :r4
]
PACKAGE = [
  :o1,
  :o2,
  :o3
]
RLOC = 0
HOLDING = 1
GOAL_IN = [
  [:o1, :r4],
  [:o2, :r2],
  [:o3, :r4]
]
IN = 2
ROOMDOOR = [
  :d02,
  :d24,
  :d14,
  :d03
]
ARMEMPTY = 3
DOOR = [
  [:c, :r2, :d02],
  [:c, :r3, :d03],
  [:r1, :r4, :d14],
  [:r2, :c, :d02],
  [:r2, :r4, :d24],
  [:r3, :c, :d03],
  [:r4, :r1, :d14],
  [:r4, :r2, :d24]
]
CLOSED = 4

Robot.problem(
  # Start
  [
    [
      :c
    ],
    [],
    [
      [:o1, :r1],
      [:o2, :r2],
      [:o3, :r2]
    ],
    [
      []
    ],
    [
      :d14,
      :d03
    ],
  ],
  # Tasks
  [
    [:achieve_goals],
    [:invisible_goal]
  ],
  # Debug
  ARGV.first == 'debug'
)