# Generated by Hype
require_relative 'domain.hddl'

# Predicates
ROOM = [
  :c,
  :r1,
  :r2,
  :r3,
  :r4,
  :r5
]
PACKAGE = [
  :o1,
  :o2,
  :o3,
  :o4,
  :o5
]
RLOC = 0
HOLDING = 1
GOAL_IN = [
  [:o1, :r4],
  [:o2, :r3],
  [:o3, :r1],
  [:o4, :r5],
  [:o5, :r5]
]
IN = 2
ROOMDOOR = [
  :d01,
  :d04,
  :d02,
  :d25,
  :d23
]
ARMEMPTY = 3
DOOR = [
  [:c, :r1, :d01],
  [:c, :r2, :d02],
  [:c, :r4, :d04],
  [:r1, :c, :d01],
  [:r2, :c, :d02],
  [:r2, :r3, :d23],
  [:r2, :r5, :d25],
  [:r3, :r2, :d23],
  [:r4, :c, :d04],
  [:r5, :r2, :d25]
]
CLOSED = 4

Robot.problem(
  # Start
  [
    [
      :c
    ],
    [],
    [
      [:o1, :r5],
      [:o2, :r4],
      [:o3, :r4],
      [:o4, :r3],
      [:o5, :r1]
    ],
    [
      []
    ],
    [
      :d04,
      :d02
    ],
  ],
  # Tasks
  [
    [:achieve_goals],
    [:invisible_goal]
  ],
  # Debug
  ARGV.first == 'debug'
)